services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=datacenter
      - POSTGRES_USER=vineeth
      - POSTGRES_DB=shelter
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5432"
  
  etl:
    build: .
    command: https://shelterdata.s3.amazonaws.com/shelter1000.csv
    depends_on:
      - db


volumes:
  db_data:

# services:
#   web:
#     build: .
#     ports:
#       - "8000:5000"
#     volumes:
#       - .:/code
#     environment:
#       FLASK_DEBUG: "true"
#   redis:
#     image: "redis:alpine"